# Here's where you define experiment-specific hyperparameters.
# You can also create lists and group parameters together into nested sub-parts.
# In Python, this is all read as a dict.

# environment/computational parameters
device: cpu
num_workers: 2

# dataset parameters
data_root: /Users/catherinebreen/Desktop/LABELED
labels: /Users/catherinebreen/code/Chapter4/4_validateRSproducts/all_labels_may2024.csv
output_path: /Users/catherinebreen/Documents/TEST
num_classes: 2 ## precip vs. none
sequenceType: 'None'

#pos_label: [1, 2, 3, 4]
#neg_label: [0]

# training hyperparameters
image_size: [224, 224]
num_epochs: 30 ##200
batch_size: 4
learning_rate: 0.001
weight_decay: 0.001

# python classifier_may24/train.py --config configs/exp_resnet50_2classes_cpu.yaml 
