# environment/computational parameters
device: cuda
num_workers: 4

# dataset parameters
data_root: datasets/data/weather
num_classes: 3 ## rain vs. snow vs.  none

# training hyperparameters
image_size: [224, 224]
num_epochs: 200
batch_size: 128
learning_rate: 0.001
weight_decay: 0.001