# Here's where you define experiment-specific hyperparameters.
# You can also create lists and group parameters together into nested sub-parts.
# In Python, this is all read as a dict.

# environment/computational parameters
device: cuda
num_workers: 4

# dataset parameters
data_root: /datadrive/vmData/weather
#train_folder: 'train'
num_classes: 2 ## weather vs. none
sequenceType: '6-12hr'

#pos_label: [1, 2, 3, 4]
#neg_label: [0]

# training hyperparameters
image_size: [224, 224]
num_epochs: 128
batch_size: 128
learning_rate: 0.001
weight_decay: 0.001

