# Here's where you define experiment-specific hyperparameters.
# You can also create lists and group parameters together into nested sub-parts.
# In Python, this is all read as a dict.

# environment/computational parameters
device: cuda
num_workers: 2 #4 

# dataset parameters: VM AURORA
data_root: /datadrive/LABELEDresize
labels: /datadrive/all_labels_may2024_updated.csv #/Users/catherinebreen/code/Chapter4/4_validateRSproducts/all_labels_may2024.csv ## UPDATE
output_path: /datadrive/classifier_results
exp_name: dataug_4_001_8010_weighted_grey_newdata_bs16s448

# model parameters
num_classes: 2 ## precip vs. none
sequenceType: 'None'

#pos_label: [1, 2, 3, 4]
#neg_label: [0]

# training hyperparameters
image_size: [448, 448]
num_epochs: 2000 ##200
batch_size: 16 #64
learning_rate: 0.001
weight_decay: 0.001

# python classifier_may24/train.py --config configs/exp_resnet50_2classes_cuda.yaml 

# ## FOR EVAL
# data_root: /Users/catherinebreen/Dropbox/Chapter4/LIBRARY
# output_path: /Users/catherinebreen/Dropbox/Chapter4/WEATHER_MODEL/classifier_results
# exp_name: baseline
# test_labels: '/Users/catherinebreen/Dropbox/Chapter4/LIBRARY_LABELS.csv'

# conda activate keypoint
# python classifier_may24/train.py --config configs/exp_resnet50_2classes_cuda.yaml 
# python classifier_may24/train_rebalance.py --config configs/exp_resnet50_2classes_cuda.yaml 