# Here's where you define experiment-specific hyperparameters.
# You can also create lists and group parameters together into nested sub-parts.
# In Python, this is all read as a dict.

# environment/computational parameters
device: cuda
num_workers: 4

# # dataset parameters: VM AURORA
# data_root: /datadrive/LABELEDresize
# labels: /datadrive/all_labels_may2024.csv #/Users/catherinebreen/code/Chapter4/4_validateRSproducts/all_labels_may2024.csv ## UPDATE
# output_path: /datadrive/classifier_results
# exp_name: dataug_4_001_8010_weighted_grey_newdata_logit
# test_labels: '/Users/catherinebreen/Dropbox/Chapter4/LIBRARY_LABELS.csv

# model parameters
num_classes: 2 ## precip vs. none
sequenceType: 'None'

#pos_label: [1, 2, 3, 4]
#neg_label: [0]

# training hyperparameters
image_size: [224, 224]
num_epochs: 2000 ##200
batch_size: 64
learning_rate: 0.001
weight_decay: 0.001

# ## FOR EVAL
data_root: /Users/catherinebreen/Desktop/LABELEDresize
#data_root: /Users/catherinebreen/Dropbox/Chapter4/LIBRARY
#test_labels: '/Users/catherinebreen/Dropbox/Chapter4/WEATHER_MODEL/classifier_results/cameras_50_50_150/valid_samples.csv'
test_labels: '/Users/catherinebreen/Dropbox/Chapter4/WEATHER_MODEL/classifier_results/cameras_100_100_50/test_samples.csv'
#test_labels: '/Users/catherinebreen/Dropbox/Chapter4/LIBRARY_LABELS.csv'
output_path: /Users/catherinebreen/Dropbox/Chapter4/WEATHER_MODEL/classifier_results
exp_name: cameras_100_100_50

# python classifier_Sept24/evaluate.py --config configs/exp_resnet50_2classes_cuda_EVAL.yaml 
# python classifier_Oct24/evaluate.py --config configs/exp_resnet50_2classes_cuda_EVAL.yaml 
