# Here's where you define experiment-specific hyperparameters.
# You can also create lists and group parameters together into nested sub-parts.
# In Python, this is all read as a dict.

# environment/computational parameters
device: cuda
num_workers: 4 #4 #4 

# dataset parameters: VM AURORA
data_root: /datadrive/vmData/LABELEDresize
labels: /datadrive/all_labels_may2024_updated_Oct12.csv
#labels: /datadrive/all_labels_may2024_updated_Sept2.csv 
#/Users/catherinebreen/code/Chapter4/4_validateRSproducts/all_labels_may2024.csv ## UPDATE

output_path: /datadrive/classifier_results
exp_name: cameras_75_75_100_weighted_wsonly_olymwyn_scand_3weight
#cameras_100_100_50_weighted_aug2
#baseline_4_001_wslab_50cams_snowis0
#dataug_4_001_8010_weighted_grey_newdata_logit2

# model parameters
num_classes: 2 ## precip vs. none
sequenceType: 'None'

#pos_label: [1, 2, 3, 4]
#neg_label: [0]

# training hyperparameters
image_size: [224, 224]
num_epochs: 2000 # 2000 ##200
batch_size: 64 # 64 #64
learning_rate: 0.001
weight_decay: 0.001

#test_labels: '/datadrive/classifier_results/baseline_4_001_30cam_wslab/valid_samples.csv'

# python classifier_may24/train.py --config configs/exp_resnet50_2classes_cuda.yaml 

# ## FOR EVAL
# data_root: /Users/catherinebreen/Dropbox/Chapter4/LIBRARY
# output_path: /Users/catherinebreen/Dropbox/Chapter4/WEATHER_MODEL/classifier_results
# exp_name: baseline
# test_labels: '/Users/catherinebreen/Dropbox/Chapter4/LIBRARY_LABELS.csv'

# conda activate keypoint
# python classifier_Oct24/train.py --config configs/exp_resnet50_2classes_cuda.yaml 
# python classifier_Sept24/train.py --config configs/exp_resnet50_2classes_cuda.yaml 
# python classifier_may24/train_rebalance.py --config configs/exp_resnet50_2classes_cuda.yaml 
# python classifier_may24/train_logit.py --config configs/exp_resnet50_2classes_cuda.yaml 

#logit = ldam
#logit2 = logit